# Generated by Django 5.0.1 on 2024-01-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('ECONOMICS', 'ECONOMICS'), ('WORLD NEWS', 'WORLD NEWS'), ('SPORTS', 'SPORTS'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('CONTACT', 'CONTACT')], max_length=20)),
            ],
        ),
    ]
