# Generated by Django 5.0.1 on 2024-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_article_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
    ]
