# Generated by Django 5.0.1 on 2024-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_article_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('ECONOMICS', 'ECONOMICS'), ('WORLD NEWS', 'WORLD NEWS'), ('SPORTS', 'SPORTS'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('CONTACT', 'CONTACT')], max_length=20, null=True),
        ),
    ]
